config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "todolists#index"
  resources :todolists do 
  	resources :todoitems
  end

resources :sessions, only: [:create, :destroy, :new]

resources :accounts , only: [:show, :edit, :update]

get '/login' => "sessions#new", as: "login"
delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/todoitem.rb
class Todoitem < ApplicationRecord
  belongs_to :todolist
  belongs_to :user
  has_and_belongs_to_many :tags


default_scope {order(due_date: :asc)}
end

app/controllers/todoitems_controller.rb
class TodoitemsController < ApplicationController

  before_action  :set_todolist

  # GET /todoitems
  # GET /todoitems.json
  def index
    @todoitems = @todolist.todoitems.paginate(page: params[:page], per_page: 5)
  end

  # GET /todoitems/1
  # GET /todoitems/1.json
  def show
       @todoitem = Todoitem.find(params[:id])

  end

  # GET /todoitems/new
  def new
    @todoitem = Todoitem.new
  end

  # GET /todoitems/1/edit
  def edit
          set_todoitem

  end

  # POST /todoitems
  # POST /todoitems.json
  def create
    @todoitem = Todoitem.new(todoitem_params)

    respond_to do |format|
          @todoitem = Todoitem.new(todoitem_params)
          @todoitem.todolist_id = @todolist.id
          @todoitem.user_id = current_user.id
          @temp = @todoitem.todolist_id
      if @todoitem.save
        format.html { redirect_to @todolist, notice: 'Todoitem was successfully created.' }
        format.json { render :show, status: :created, location: @todoitem }
      else
        format.html { redirect_to @todolist, notice: "Todoitem was NOT successfully created. #{@temp}" }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todoitems/1
  # PATCH/PUT /todoitems/1.json
  def update
    set_todoitem
    respond_to do |format|
      if @todoitem.update(todoitem_params)
        format.html { redirect_to @todolist, notice: 'Todoitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @todoitem }
      else
        format.html { render :edit }
        format.json { render json: @todoitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todoitems/1
  # DELETE /todoitems/1.json
  def destroy
        set_todoitem
    @todoitem.destroy
    respond_to do |format|
      format.html { redirect_to @todolist, notice: 'Todoitem was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todoitem
      @todoitem = Todoitem.find(params[:id])
    end

    def set_todolist 
  @todolist = Todolist.find(params[:todolist_id])
end 

    # Never trust parameters from the scary internet, only allow the white list through.
    def todoitem_params
      params.require(:todoitem).permit(:due_date, :task_title, :description, :done)
    end
end

app/helpers/todoitems_helper.rb
module TodoitemsHelper
end

app/views/todoitems/_form.html.erb
<%= form_for(todoitem) do |f| %>
  <% if todoitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todoitem.errors.count, "error") %> prohibited this todoitem from being saved:</h2>

      <ul>
      <% todoitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.text_field :due_date %>
  </div>

  <div class="field">
    <%= f.label :task_title %>
    <%= f.text_field :task_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :done %>
    <%= f.text_field :done %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todoitems/_todoitem.html.erb
<div class="todoitem">
<div>

<% if todoitem.done == true %> 
<span class = "green">
<%else %> 
<span class = "red">
<% end %>
<%= "#{todoitem.due_date}" %> 
</span>
<%=link_to "#{todoitem.task_title}", todolist_todoitem_path(@todolist, todoitem) %>
<div>
</div>

app/views/todoitems/edit.html.erb
<h1>Editing Todoitem</h1>

<%= form_for([@todolist, @todoitem]) do |f| %>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_select :due_date %>
  </div>

  <div class="field">
    <%= f.label :task_title %>
    <%= f.text_field :task_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :done %>
    <%= f.check_box :done %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', todolist_todoitem_path(@todolist, @todoitem) %>

app/views/todoitems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todoitems</h1>

<table>
  <thead>
    <tr>
      <th>Due date</th>
      <th>Task title</th>
      <th>Description</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todoitems.each do |todoitem| %>
      <tr>
        <td><%= todoitem.due_date %></td>
        <td><%= todoitem.task_title %></td>
        <td><%= todoitem.description %></td>
        <td><%= todoitem.done %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @todoitems %>

app/views/todoitems/new.html.erb
<h1>New Todoitem</h1>
<p id="notice"><%= notice %></p>


<%= form_for([@todolist, @todoitem]) do |f| %>

  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_select :due_date %>
  </div>

  <div class="field">
    <%= f.label :task_title %>
    <%= f.text_field :task_title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', todolist_path(@todolist)%>

app/views/todoitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<p id="notice"><%= notice %></p>
<h1>
  <%= @todoitem.task_title %>
</h1>


<div>
Due on: <%= @todoitem.due_date %>
</div>
<div>
Status: <%= 
if @todoitem.done == true
	"Done"
else
	"Not Done"
end
	%>
</div>
<div>
<%= @todoitem.description %>
</div>



<%= link_to 'Edit Todo Item', edit_todolist_todoitem_path(@todolist, @todoitem) %> |
<%= link_to 'Delete Todo Item', todolist_todoitem_path(@todolist, @todoitem), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', todolist_path(@todolist) %>