config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "todolists#index"
  resources :todolists do 
  	resources :todoitems
  end

resources :sessions, only: [:create, :destroy, :new]

resources :accounts , only: [:show, :edit, :update]

get '/login' => "sessions#new", as: "login"
delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/todolist.rb
class Todolist < ApplicationRecord
  belongs_to :user
  has_many :todoitems

default_scope {order(list_due_date: :asc)}
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = current_user.todolists.paginate(page: params[:page], per_page: 5)

  end
  # GET /todolists/1
  # GET /todolists/1.json
  def show
    @itemslist = current_user.todolists.find(params[:id]).todoitems.paginate(page: params[:page], per_page: 5)
  end

  # GET /todolists/new
  def new
    @todolist = current_user.todolists.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = current_user.todolists.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: 'Todolist was successfully created.' }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'Todolist was successfully updated.' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url, notice: 'Todolist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contains_todoitems(todolist)
  todoitems = todolist.todoitems.all
  color = ""
  if todoitems.empty? || item_completed(todolist)
    color = "green"
  else
    color = "red"
  end
  return color
end
helper_method :contains_todoitems

def item_completed(todolist)
  todoitems = todolist.todoitems.all
  @bool = false
  todoitems.each do |todoitem| 
    if todoitem.done
      @bool = true
    else
      @bool = false
    end
  end
  return @bool
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = current_user.todolists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:list_due_date, :list_name)
    end
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/todolists/_form.html.erb
<%= form_for(todolist) do |f| %>
  <% if todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_due_date %>
    <%= f.date_select :list_due_date %>
  </div>

  <div class="field">
    <%= f.label :list_name %>
    <%= f.text_field :list_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todolists</h1>

<table>

  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><span class = <%= contains_todoitems(todolist) %>><%= todolist.list_due_date %></span></td>
        <td><%= link_to "#{todolist.list_name}", todolist %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= will_paginate @todolists %>

<%= link_to 'New Todolist', new_todolist_path %>

app/views/todolists/new.html.erb
<h1>New Todolist</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Back', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  
  <%= @todolist.list_name %>
</h1>
<p></p>
<h2>
  <strong>List due date:</strong>
  <%= @todolist.list_due_date %>
</h2>

</p>

<% @itemslist.each do |todoitem| %>
      <tr>
        <%= render todoitem %>
      </tr>
    <% end %>
<%= will_paginate @itemslist %>


<%= link_to 'Edit Todo List', edit_todolist_path(@todolist) %> |

<%= link_to 'Delete Todo List', @todolist, method: :delete, data: { confirm: 'Are you sure?' } %> | 

<%= link_to 'Back', todolists_path %>

</p>
<%= link_to 'Add new Todo Item', new_todolist_todoitem_path(@todolist) %>