config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "todolists#index"
  resources :todolists do 
  	resources :todoitems
  end

resources :sessions, only: [:create, :destroy, :new]

resources :accounts , only: [:show, :edit, :update]

get '/login' => "sessions#new", as: "login"
delete '/logout' => "sessions#destroy", as: "logout"

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user

  validate :gendercheck, :agecheck

def gendercheck 

	if(gender.nil?) 
		errors.add(:gender, "Gender cannot be Empty. Please specify value")
	elsif ["male", "female", "n/a"].exclude?(gender.downcase)

		errors.add(:gender, "Specifed value for gender must be male, female or N/A, you used #{gender.downcase}")
	end

	end

	def agecheck 
		if(age.nil?) 
		errors.add(:age, "Age cannot be Empty. Please specify value between 20 and 100")
	elsif (age < 20 || age > 100) 
			errors.add(:age, "Please enter an age between 20 and 100")
		end
	end	
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update]

  # GET /accounts
  # GET /accounts.json
  def index
        @accounts = accounts.all

  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.account.new
  end

  # GET /accounts/1/edit
  def edit
  end


  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update

    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.account
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :gender, :age)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>
<%= link_to 'Show', @account %> |
<%= link_to 'Back', account_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.first_name %></td>
        <td><%= account.last_name %></td>
        <td><%= account.gender %></td>
        <td><%= account.age %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Info</h1>


<p>
  <strong>First name:</strong>
  <%= @account.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @account.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @account.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @account.age %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', account_path %>